import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import sequelize, { Rating } from "../connectors/sequelize";

const Home: NextPage = ({ ratings = [] }) => {
  console.log("client", ratings);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>🗽🍕 Rate Your Slice 🍕🗽 </h1>

        <p className={styles.description}>
          My personal ratings for all the slices I&apos;ve tried in NYC.
        </p>

        <h3 className={styles.description}>Current Leaderboard</h3>
        {ratings?.length > 0 && (
          <ul>
            {ratings.map(({ id, name, location, slice, rating }, i) => (
              <li key={id}>
                🍕 {name}, {location} - {slice} Slice - {rating}
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  let ratings = [];
  
  try {
    await sequelize.authenticate();

    const ratingsData = await Rating.findAll();

    ratings = JSON.stringify(ratingsData);
    ratings = JSON.parse(ratings);

    if (ratings?.length < 1) {
      ratings = [
        {
          name: "L'Industrie Pizzeria",
          location: "Brooklyn",
          slice: "Fig Jam & Bacon",
          rating: 8.5,
        },
        {
          name: "Paulie Gee's",
          location: "Madison Square Garden",
          slice: "Cheese",
          rating: 8,
        },
      ];
    }

    console.log("here", typeof ratings);
  } catch (error) {
    console.log(error.message);
  }

  console.log(ratings);

  return {
    props: { ratings },
  };
}

export default Home;
